version: "3.2"
services:
  app:
    command: npm run dev
    depends_on:
      - proxy
      - mock
      - nginx
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/dist
    ports:
      - "9229:9229"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      HTTP_PROXY: http://nginx:8080
      #HTTPS_PROXY: https://nginx:8080
      #NO_PROXY: localhost,127.0.0.1
  mock:
    build: ./mock
    ports:
      - "1880:1880"
    volumes:
      - ./mock/src:/data
  proxy:
    build: ./proxy
    depends_on:
      - mock
    volumes:
      - ./proxy:/usr/app
  nginx:
    image: nginx:1.16-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
