version: "3.2"
services:
  app:
    command: npm run dev
    depends_on:
      - proxy
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/dist
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      HTTPS_PROXY: https://proxy:8001
      NO_PROXY: localhost,127.0.0.1
  proxy:
    build: ./proxy
    volumes:
      - ./proxy:/usr/app